services:
  - type: web
    name: expo-stores
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: SESSION_MAX_AGE_MS
        value: 2592000000
