apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: expo-stores
data:
  NODE_ENV: "production"
  PORT: "5000"
  ENABLE_CSRF: "true"
  COOKIE_SECURE: "true"
  CORS_ORIGIN: "https://expo.example.com"
  ENABLE_DEBUG_ROUTES: "false"
  SEED_DEFAULTS: "false"
