apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: expo-stores
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: __REPLACE_WITH_USERNAME__
  MONGO_INITDB_ROOT_PASSWORD: __REPLACE_WITH_STRONG_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: expo-stores
type: Opaque
stringData:
  MONGO_URI: __REPLACE_WITH_MONGO_URI__
  COOKIE_SECRET: __REPLACE_WITH_RANDOM_SECRET__
